### ISSUE TITLE
NameError attempting to run a build with a worker on my local machine

### ISSUE THREAD

**Issue by gmarkall** [Anaconda-Server/conda-server-build#60]
I am following the directions at: http://docs.binstar.org/build-config.html#BuildWorkers

I set up a queue for dynd with

```
$ binstar-build queue --create dynd/q1
```

Then I started the build worker:

```
$ binstar-build worker dynd/q1
Using binstar api site https://api.anaconda.org
Starting worker:
User: dynd
Queue: q1
Platform: linux-64
Working Forever
Worker is waiting for the next job
```

Then I submitted a build from another terminal:

```
$ binstar-build submit . --queue dynd/q1
```

The following output came out of the build worker:

```
Starting build, 55a7e96094b2c15deecd93c1, dynd/libdynd#15.0
Setting alarm to terminate build after 216000 seconds
Building on worker pumpkin (platform linux-64)
Starting build dynd/libdynd#15.0
Fetching build data
Wrote build data to build_data/55a7e96094b2c15deecd93c1.tar.bz2
Running command: (iotimeout=300)
/home/gmarkall/work/bsb-worker/build_scripts/55a7e96094b2c15deecd93c1.sh --api-token dy-024442a6-6354-44a4-959c-59ab342ca789 --build-tarball /home/gmarkall/work/bsb-worker/build_data/55a7e96094b2c15deecd93c1.tar.bz2
Build Error: An unhandled exception occurred in the build worker---
Traceback (most recent call last):
  File "/home/gmarkall/miniconda3/lib/python3.4/site-packages/binstar_build_client/worker/worker.py", line 211, in build
    instructions=instructions)
  File "/home/gmarkall/miniconda3/lib/python3.4/site-packages/binstar_build_client/worker/worker.py", line 259, in run
    p0 = BufferedPopen(args, stdout=build_log, iotimeout=iotimeout, cwd=working_dir)
  File "/home/gmarkall/miniconda3/lib/python3.4/site-packages/binstar_build_client/worker/utils/buffered_io.py", line 42, in __init__
    self._iostream = IOStream(self.stdout, self._output, iotimeout, timeout, self.timeout_callback)
  File "/home/gmarkall/miniconda3/lib/python3.4/site-packages/binstar_build_client/worker/utils/streamio.py", line 35, in __init__
    if isinstance(line_iterator, file):
NameError: name 'file' is not defined

---[NameError] name 'file' is not defined 
Traceback (most recent call last):
  File "/home/gmarkall/miniconda3/lib/python3.4/site-packages/binstar_build_client/worker/worker.py", line 138, in _handle_job
    failed, status = self.build(job_data)
  File "/home/gmarkall/miniconda3/lib/python3.4/site-packages/binstar_build_client/worker/worker.py", line 211, in build
    instructions=instructions)
  File "/home/gmarkall/miniconda3/lib/python3.4/site-packages/binstar_build_client/worker/worker.py", line 259, in run
    p0 = BufferedPopen(args, stdout=build_log, iotimeout=iotimeout, cwd=working_dir)
  File "/home/gmarkall/miniconda3/lib/python3.4/site-packages/binstar_build_client/worker/utils/buffered_io.py", line 42, in __init__
    self._iostream = IOStream(self.stdout, self._output, iotimeout, timeout, self.timeout_callback)
  File "/home/gmarkall/miniconda3/lib/python3.4/site-packages/binstar_build_client/worker/utils/streamio.py", line 35, in __init__
    if isinstance(line_iterator, file):
NameError: name 'file' is not defined
 
Build Duration 5 seconds
Worker is waiting for the next job
```

and the output of the build is at https://anaconda.org/dynd/libdynd/builds/15/0

What went wrong? Is there some way around this issue?

**Comment by srossross** [comment]
Are you running this in python3? can you try running the worker in python2?

**Comment by gmarkall** [comment]
I am - I will try with Python 2.

**Comment by gmarkall** [comment]
That got a little further, but now it hangs in `conda clean -pt`: https://anaconda.org/dynd/libdynd/builds/17/0

**Comment by srossross** [comment]
Try running: 
```
 conda config --set always_yes true 
```

**Comment by gmarkall** [comment]
Thanks, that got over the issue. I've created a PR to update the docs.
