### ISSUE TITLE
Error during automatic start up of new submission

### ISSUE THREAD

**Issue by mutirri** [Anaconda-Server/conda-server-build#66]
**All** machines reported **the same** message when crashed:
```
Using binstar api site https://api.anaconda.org
Starting worker:
User: binstar
Queue: continuum
Platform: linux-64
Working Forever
Removing worker 55b80a4b3664bf6a74552aa4
[NotFound] Not Found: Nothing matches the given URI ([POST] https://api.anaconda.org/build-worker/binstar/continuum/55b80a4b3664bf6a74552aa4/jobs -> 404) 
Traceback (most recent call last):
  File "/home/binstar/miniconda/bin/binstar-build", line 6, in <module>
    sys.exit(main())
  File "/home/binstar/miniconda/lib/python2.7/site-packages/binstar_build_client/scripts/build.py", line 31, in main
    version=version)
  File "/home/binstar/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/home/binstar/miniconda/lib/python2.7/site-packages/binstar_build_client/commands/worker.py", line 47, in main
    worker.work_forever()
  File "/home/binstar/miniconda/lib/python2.7/site-packages/binstar_build_client/worker/worker.py", line 79, in work_forever
    self._build_loop()
  File "/home/binstar/miniconda/lib/python2.7/site-packages/binstar_build_client/worker/worker.py", line 180, in _build_loop
    for job_data in self.job_loop():
  File "/home/binstar/miniconda/lib/python2.7/site-packages/binstar_build_client/worker/worker.py", line 99, in job_loop
    job_data = bs.pop_build_job(args.username, args.queue, self.worker_id)
  File "/home/binstar/miniconda/lib/python2.7/site-packages/binstar_build_client/mixins/build_queue.py", line 36, in pop_build_job
    self._check_response(res, [200])
  File "/home/binstar/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 160, in _check_response
    raise ErrCls(msg, res.status_code)
NotFound: (u'Not Found: Nothing matches the given URI ([POST] https://api.anaconda.org/build-worker/binstar/continuum/55b80a4b3664bf6a74552aa4/jobs -> 404)', 404)
```

The recipes that might cause some problems (they were submitted as last and are not properly cleaned up from worker internal `build_scripts` dir) are:
A)
user: @jreback
recipe: pandas
B)
user: @pitrou 
pkg recipe: numba

Maybe these recipes influence somehow on how binstar worker is behaving.

**Comment by mutirri** [comment]
Still, from time to time is showing up the below error, what kills workers:
```
[NotFound] Not Found: Nothing matches the given URI ([POST] https://api.anaconda.org/build-worker/binstar/public/55d255c218baeb67913597ae/jobs -> 404) 
Traceback (most recent call last):
  File "/home/ec2-user/miniconda/bin/binstar-build", line 6, in <module>
    sys.exit(main())
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/binstar_build_client/scripts/build.py", line 31, in main
    version=version)
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/binstar_build_client/commands/docker_worker.py", line 48, in main
    woker.work_forever()
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/binstar_build_client/worker/worker.py", line 79, in work_forever
    self._build_loop()
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/binstar_build_client/worker/worker.py", line 180, in _build_loop
    for job_data in self.job_loop():
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/binstar_build_client/worker/worker.py", line 99, in job_loop
    job_data = bs.pop_build_job(args.username, args.queue, self.worker_id)
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/binstar_build_client/mixins/build_queue.py", line 36, in pop_build_job
    self._check_response(res, [200])
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 159, in _check_response
    raise ErrCls(msg, res.status_code)
NotFound: (u'Not Found: Nothing matches the given URI ([POST] https://api.anaconda.org/build-worker/binstar/public/55d255c218baeb67913597ae/jobs -> 404)', 404)
```

**Comment by srossross** [comment]
This will probably be fixed with #89
